# Sdapter: mysql2
#   encoding: utf8
#     database: Rails_development
#       pool: 5
#         username: railsuser
#           password: mypasswordQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development:
  adapter: mysql2
  database: myapp_development
  encoding: utf8
  pool: 5
  timeout: 5000
  username: root
  password: <%= ENV['RAILS_DATABASE_PASSWORD'] %>
  host: localhost

test:
  adapter: mysql2
  database: myapp_test
  encoding: utf8
  pool: 5
  timeout: 5000
  username: root
  password: <%= ENV['RAILS_DATABASE_PASSWORD'] %>
  host: localhost

production:
  adapter: mysql2
  database: myapp_production
  encoding: utf8
  pool: 5
  timeout: 5000
  username: root
  password: <%= ENV['RAILS_DATABASE_PASSWORD'] %>
  host: localhost
